namespace ShopAssistant.Contracts.Models.Analytics;

/// <summary>
/// Represents a single attempt to answer a user question from the FAQ knowledge base.
/// </summary>
public class FaqQueryLogEntry
{
    /// <summary>
    /// Unique record ID (autogenerated on insert).
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// The user identifier who asked the question.
    /// </summary>
    public string UserId { get; set; } = null!;

    /// <summary>
    /// The external system/shop/channel where the question was asked.
    /// </summary>
    public string ExternalSystem { get; set; } = null!;

    /// <summary>
    /// The text of the user question sent for FAQ lookup.
    /// </summary>
    public string InputText { get; set; } = null!;

    /// <summary>
    /// Topic of the FAQ question (useful for reporting, analytics, and grouping by FAQ category).
    /// </summary>
    public string? Topic { get; set; }

    /// <summary>
    /// The language code of the question (e.g., "en", "ru").
    /// </summary>
    public string Language { get; set; } = null!;

    /// <summary>
    /// Date and time when the FAQ lookup was performed (UTC).
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// True if an answer was found in the FAQ.
    /// </summary>
    public bool FaqHit { get; set; }

    /// <summary>
    /// Optional: The FAQ ID that was matched (if any).
    /// </summary>
    public long? FaqId { get; set; }
}